import { pgTable, uuid, text, timestamp, boolean, integer, numeric, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  firstName: text('first_name'),
  lastName: text('last_name'),
  role: text('role').notNull().default('seller'),
  avatarUrl: text('avatar_url'),
  phone: text('phone'),
  active: boolean('active').default(true),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  lastLoginAt: timestamp('last_login_at'),
  notificationPreferences: jsonb('notification_preferences'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const companies = pgTable('companies', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  domain: text('domain'),
  industry: text('industry'),
  size: text('size'),
  revenue: numeric('revenue', { precision: 12, scale: 2 }),
  address: text('address'),
  city: text('city'),
  country: text('country'),
  phone: text('phone'),
  website: text('website'),
  instagram: text('instagram'),
  facebook: text('facebook'),
  linkedin: text('linkedin'),
  notes: text('notes'),
  ownerId: uuid('owner_id').references(() => users.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const contacts = pgTable('contacts', {
  id: uuid('id').primaryKey().defaultRandom(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').unique(),
  phone: text('phone'),
  jobTitle: text('job_title'),
  department: text('department'),
  companyId: uuid('company_id').references(() => companies.id),
  ownerId: uuid('owner_id').references(() => users.id),
  leadScore: integer('lead_score').default(0),
  lifecycleStage: text('lifecycle_stage').default('lead'),
  status: text('status').default('active'),
  source: text('source'),
  notes: text('notes'),
  customFields: jsonb('custom_fields'),
  lastActivityAt: timestamp('last_activity_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const deals = pgTable('deals', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  companyId: uuid('company_id').references(() => companies.id),
  contactId: uuid('contact_id').references(() => contacts.id),
  ownerId: uuid('owner_id').references(() => users.id),
  stage: text('stage').notNull(),
  value: numeric('value', { precision: 12, scale: 2 }).default('0'),
  currency: text('currency').default('EUR'),
  probability: integer('probability').default(50),
  expectedCloseDate: timestamp('expected_close_date'),
  closedAt: timestamp('closed_at'),
  wonReason: text('won_reason'),
  lostReason: text('lost_reason'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const tickets = pgTable('tickets', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  status: text('status').default('open'),
  priority: text('priority').default('medium'),
  category: text('category'),
  companyId: uuid('company_id').references(() => companies.id),
  contactId: uuid('contact_id').references(() => contacts.id),
  assigneeId: uuid('assignee_id').references(() => users.id),
  reporterId: uuid('reporter_id').references(() => users.id),
  resolution: text('resolution'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  resolvedAt: timestamp('resolved_at'),
});

export const tasks = pgTable('tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status').default('todo'),
  dueDate: timestamp('due_date'),
  priority: text('priority').default('medium'),
  companyId: uuid('company_id').references(() => companies.id),
  contactId: uuid('contact_id').references(() => contacts.id),
  dealId: uuid('deal_id').references(() => deals.id),
  assigneeId: uuid('assignee_id').references(() => users.id),
  createdById: uuid('created_by_id').references(() => users.id),
  reminderAt: timestamp('reminder_at'),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const activities = pgTable('activities', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: text('type').notNull(),
  subject: text('subject').notNull(),
  content: text('content'),
  direction: text('direction'),
  duration: integer('duration'),
  outcome: text('outcome'),
  companyId: uuid('company_id').references(() => companies.id),
  contactId: uuid('contact_id').references(() => contacts.id),
  dealId: uuid('deal_id').references(() => deals.id),
  ticketId: uuid('ticket_id').references(() => tickets.id),
  taskId: uuid('task_id').references(() => tasks.id),
  userId: uuid('user_id').references(() => users.id),
  attachments: text('attachments').array(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const pipelineStages = pgTable('pipeline_stages', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  position: integer('position').notNull(),
  color: text('color').default('#64748b'),
  probabilityDefault: integer('probability_default').default(50),
  isWon: boolean('is_won').default(false),
  isLost: boolean('is_lost').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

export const integrations = pgTable('integrations', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: text('type').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  expiresAt: timestamp('expires_at'),
  userId: uuid('user_id').references(() => users.id),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const prospectSearches = pgTable('prospect_searches', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  sector: text('sector').notNull(),
  zone: text('zone').notNull(),
  zoneType: text('zone_type').notNull().default('barrio'),
  keywords: text('keywords').notNull(),
  status: text('status').notNull().default('pending'),
  totalResults: integer('total_results').default(0),
  enrichedCount: integer('enriched_count').default(0),
  importedCount: integer('imported_count').default(0),
  apifyRunId: text('apify_run_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const prospectResults = pgTable('prospect_results', {
  id: uuid('id').primaryKey().defaultRandom(),
  searchId: uuid('search_id').references(() => prospectSearches.id).notNull(),
  googlePlaceId: text('google_place_id').notNull(),
  name: text('name').notNull(),
  address: text('address'),
  district: text('district'),
  neighborhood: text('neighborhood'),
  phone: text('phone'),
  website: text('website'),
  googleRating: numeric('google_rating', { precision: 2, scale: 1 }),
  googleReviewCount: integer('google_review_count').default(0),
  category: text('category'),
  email: text('email'),
  instagram: text('instagram'),
  contactName: text('contact_name'),
  contactTitle: text('contact_title'),
  tripAdvisorRating: numeric('tripadvisor_rating', { precision: 2, scale: 1 }),
  logoUrl: text('logo_url'),
  enrichmentStatus: text('enrichment_status').notNull().default('pending'),
  enrichmentData: jsonb('enrichment_data'),
  reviewStatus: text('review_status').notNull().default('pending'),
  importedAt: timestamp('imported_at'),
  importedContactId: uuid('imported_contact_id').references(() => contacts.id),
  importedCompanyId: uuid('imported_company_id').references(() => companies.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export * from './landing';
export * from './agents';
